// cartSlice.js
import {createSlice} from '@reduxjs/toolkit';

// Create a slice for managing the cart state using createSlice
const cartSlice = createSlice({
  name: 'cart', // Name of the slice
  initialState: [], // Initial state of the cart is an empty array
  reducers: {
    addToCart: (state, action) => {
      state.push(action.payload); // Add the payload (item) to the cart state
    },
    removeFromCart: (state, action) => {
      return state.filter(item => item.id !== action.payload.id); // Remove the item from the cart by filtering based on the payload (item)
    },
  },
});

// Export actions generated by createSlice
export const {addToCart, removeFromCart} = cartSlice.actions;

// Export the reducer generated by createSlice
export default cartSlice.reducer;
