// reducers/productSlice.js
import {createSlice} from '@reduxjs/toolkit';

// Create a slice using createSlice from Redux Toolkit
const productSlice = createSlice({
  // Specify the name for the slice
  name: 'product',

  // Define the initial state for the slice
  initialState: {
    products: [],
  },

  // Define the reducers for the slice
  reducers: {
    // Define a reducer function named setProducts
    setProducts: (state, action) => {
      // Update the state by setting the products array to the payload of the action
      state.products = action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const {setProducts} = productSlice.actions;

// Export the reducer function generated by createSlice
export default productSlice.reducer;
